# Generated by Django 3.2.3 on 2022-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper_and_analyzer', '0003_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='image',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='dataset',
            name='link',
            field=models.CharField(default=None, max_length=80),
        ),
        migrations.AddField(
            model_name='dataset',
            name='website',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
